# BEST FACTORIZED
python main.py \
--bs 1 \
--drop_het 0 \
--epochs 30 \
--gat_conv_num_heads 2 \
--global_lr 0.001 \
--graph_conv_in_dim 80 \
--net factorized \
--num_agg_nodes 1 \
--num_gat_layers 2 \
--scene_mean 1 \
--social_baseline 0 \
--test 0 \
--out_dir /home/shounak_rtml/11777/MTAG/results/factorized \
--trials 1 \
--seq_len 150 \
--gran word \
--test 0 
